
import 'package:my_visitor/features/ML/data/models/hosam_model.dart';

List<HosamModel> historicalData = [
  HosamModel(name: "Akhenaten", aboutMe: "came to power as the pharaoh of Egypt in either the year 1353 or 1351 BCE and reigned for roughly 17 years during the 18th dynasty of Egypt’s New Kingdom. Akhenaten became best known to modern scholars for the new religion he created that centered on the Aten. In Akhenaten’s new religion, this figure generally came to be represented as a sun disk and is best understood as the light produced by the sun itself.  The king ascended the throne under his birth name, Amenhotep IV, but in his fifth regnal year, he changed his name to one that better reflected his religious ideas (Amenhotep = “Amun is satisfied,” Akhenaten = “Effective for Aten”). Shortly after this first significant step, Akhenaten initiated a series of changes in Egyptian religion, art and writing that appeared to coincide with the jubilees of his deified father, Amenhotep III, and the Aten."),
  HosamModel(name: "Bent-pyramid-for-senefru", aboutMe: "In the heart of ancient Egypt's historical legacy stand the remarkable Dahshur Pyramids, a testament to the architectural prowess and cultural significance of this ancient civilization. Among these awe-inspiring structures, the Bent Pyramid of Pharaoh Sneferu commands attention with its unique design and enigmatic history. The Dahshur Pyramids are an ancient site in Egypt, located just south of Cairo. They are one of the most famous and impressive monuments in the world, and have been a source of fascination for centuries. The Dahshur Pyramids consist of two distinct pyramids: the Bent Pyramid and the Red Pyramid. Both were built during the Fourth Dynasty (2575-2465 BCE) under the rule of Pharaoh Sneferu, who is credited with developing the pyramid shape. The Bent Pyramid is one of the earliest examples of a true pyramid in Egypt, and is considered to be a masterpiece of ancient engineering. It is believed to have been built as a tomb for Pharaoh Sneferu, who was the first king to use stone instead of mud-brick or wood for his monuments. The Bent Pyramid stands at 105 meters tall and has two distinct sections: a lower section that rises at 54 degrees, and an upper section that rises at 43 degrees. This unique shape has earned it its name; it looks like it has been bent at its midpoint."),
  

  HosamModel(name: "Colossoi-of-Memnon", aboutMe: ""),
  HosamModel(name: "Goddess-Isis-with-her-child", aboutMe: ""),
  HosamModel(name: "Hatshepsu", aboutMe: ""),
  HosamModel(name: "Hatshepsut-face", aboutMe: ""),
  HosamModel(name: "Khafre-Pyramid", aboutMe: ""),
  HosamModel(name: "Mask-of-Tutankhamun", aboutMe: ""),
  HosamModel(name: "Nefertiti", aboutMe: ""),
  HosamModel(name: "Pyramid_of_Djoser", aboutMe: ""),
  HosamModel(name: "Ramessum", aboutMe: ""),
  HosamModel(name: "Ramses-II-Red-Granite-Statue", aboutMe: ""),
  HosamModel(name: "Statue-of-King-Zose", aboutMe: ""),
  HosamModel(name: "Statue-of-Tutankhamun-with-Ankhesenamun", aboutMe: ""),
  HosamModel(name: "Temple_of_Isis_in_Philae", aboutMe: ""),
  HosamModel(name: "Temple_of_Kom_Ombo", aboutMe: ""),
  HosamModel(name: "The-Great-Temple-of-Ramesses-II", aboutMe: ""),
  HosamModel(name: "amenhotep-iii-and-tiye", aboutMe: ""),
  HosamModel(name: "bust-of-ramesses-ii", aboutMe: ""),
  HosamModel(name: "menkaure-pyramid", aboutMe: ""),
  HosamModel(name: "sphinx", aboutMe: ""),
  HosamModel(name: "Abu Haggag Mosque", aboutMe: ""),
  HosamModel(name: "Abu Simbel Temples", aboutMe: ""),
  HosamModel(name: "Abu el-Abbas el-Mursi Mosque", aboutMe: ""),
  HosamModel(name: "Aga Khan Mausoleum", aboutMe: ""),
  HosamModel(name: "Agiba Beach", aboutMe: ""),
  HosamModel(name: "Al-Azhar Mosque", aboutMe: ""),
  HosamModel(name: "Al-Azhar Park", aboutMe: ""),
  HosamModel(name: "Alexandria Opera House", aboutMe: ""),
  HosamModel(name: "Amenhotep III Sun Temple", aboutMe: ""),
  HosamModel(name: "Aswan High Dam", aboutMe: ""),
  HosamModel(name: "Bagawat", aboutMe: ""),
  HosamModel(name: "Bayt Al-Suhaymi", aboutMe: ""),
  HosamModel(name: "Bibliotheca Alexandrina", aboutMe: ""),
  HosamModel(name: "Citadel of Qaitbay", aboutMe: ""),
  HosamModel(name: "Dahshur Pyramid", aboutMe: ""),
  HosamModel(name: "Deir el-Bahari", aboutMe: ""),
  HosamModel(name: "Deir el-Medina", aboutMe: ""),
  HosamModel(name: "Edfu Temple", aboutMe: ""),
  HosamModel(name: "Egyptian National Military Museum", aboutMe: ""),
  HosamModel(name: "Fatimid Cemetery", aboutMe: ""),
  HosamModel(name: "Gayer Anderson Museum", aboutMe: ""),
  HosamModel(name: "Great Sphinx of Giza", aboutMe: ""),
  HosamModel(name: "Hanging Church", aboutMe: ""),
  HosamModel(name: "Hypostyle Hall", aboutMe: ""),
  HosamModel(name: "Karnak Temple", aboutMe: ""),
  HosamModel(name: "Luxor Temple", aboutMe: ""),
  HosamModel(name: "Montaza Palace", aboutMe: ""),
  HosamModel(name: "Pyramids", aboutMe: ""),
  HosamModel(name: "Qubbet el-Hawa", aboutMe: ""),
  HosamModel(name: "Ramesseum", aboutMe: ""),
  HosamModel(name: "Saint George Church", aboutMe: ""),
  HosamModel(name: "Saqqara Pyramid", aboutMe: ""),
  HosamModel(name: "St. Catherine's Monastery", aboutMe: ""),
  HosamModel(name: "Temple of Isis in Philae", aboutMe: ""),
  HosamModel(name: "Temple of Kom Ombo", aboutMe: ""),
  HosamModel(name: "Trajan's Kiosk", aboutMe: ""),
  HosamModel(name: "Unfinished Obelisk", aboutMe: ""),
];

